#!/bin/bash -l

# Put the right credentials in Vault
vault kv put kv/db/postgres/product-db-creds \
    username=postgres \
    password=password

# Remove the shared credentials file
rm /share/postgres-product-creds.txt

# Restart the Product API deployment
kubectl rollout restart deployment products-api-deployment

# Give the pod time to cycle
sleep 5

exit 0
