# Copyright (c) HashiCorp, Inc.
# SPDX-License-Identifier: MPL-2.0

version: "3"
virtualmachines:
- name: kubernetes
  image: instruqt-hashicorp/kubernetes-base-helm3-1-0-20240318-215830
  shell: /bin/bash
  machine_type: n1-standard-2
