#!/bin/bash -l

# Write the necessary policies
vault policy write dba-operator policies/dba-operator-policy.hcl

# Enable the Userpass auth method
vault auth enable userpass

# Create the DBA Dan user with the dba-operator policy attached
vault write auth/userpass/users/dba-dan password=dba-dan policies=dba-operator

# Unset the VAULT_TOKEN so it doesn't take precedence over logging in with DBA Dan
unset VAULT_TOKEN

# Log in with DBA Dan
vault login -method=userpass username=dba-dan password=dba-dan

exit 0
