#!/bin/bash -l

# Check that both of the necesssary policies were written
vault policy read dba-operator || fail-message "You did not upload a policy for dba-operator."

# Make sure the Userpass auth method was enabled
type_at_userpass_path=$(vault auth list -format=json | jq -r '.["userpass/"]["type"]')

if [ ! "userpass" = "$type_at_userpass_path" ]; then
    fail-message "You haven't enabled the Userpass auth method yet."
fi

# Make sure that they logged in at least one time with the DBA Dan user
num_userpass_login_leases=$(vault list -format=json sys/leases/lookup/auth/userpass/login | jq ". |  length")

if [ $num_userpass_login_leases -lt 1 ]; then
    fail-message "You have logged in with the Userpass method $num_userpass_login_leases times. You need to log in with DBA Dan at least 1 time."
    exit 1
fi
