#!/bin/bash -l

# Replace Values in the Products API deployment with the new path we just configured.
sed -i 's/kv\/db\/postgres\/product-db-creds/database\/creds\/products-api/g' /root/k8s/products-api.yml

# Update the Products API deployment
kubectl apply -f /root/k8s/products-api.yml

# Update the products-api-policy.hcl policy
sed -i 's/kv\/db\/postgres\/product-db-creds/database\/creds\/products-api/g' /root/policies/products-api-policy.hcl

# Update the products-api policy
vault policy write products-api policies/products-api-policy.hcl

# Restart the deployment to take the new changes
kubectl rollout restart deployment products-api-deployment

exit 0
